### ISSUE TITLE
display not refreshed while stepping through code

### ISSUE THREAD

**Issue by kbrock** [mappum/0x10code#11]
Hello, great website.

I was working with a hello world.
When I step through the code, it doesn't seem to refresh the display.
When I click "run", it displays just fine.

If you would like more information, please let me know.
Thanks
Keenan

--- program I was running ---
set i, 0
:loop
set a, [hello_world + i]
ife a, c
   set pc, end
bor a, 0x2100
set [0x8000 + i], a
add i, 1
set pc, loop

:end
set pc, end

:hello_world dat "Hello World!", 0

**Comment by mappum** [comment]
Interesting, I'll fix that. Thanks.
