### ISSUE TITLE
has no method 'createServer'

### ISSUE THREAD

**Issue by wub** [mappum/0x10code#13]
After following the install procedures, on `node app.js` execution I get this error:

``` bash
node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object function createApplication() {
  var app = connect();
  utils.merge(app, proto);
  app.request = { __proto__: req };
  app.response = { __proto__: res };
  app.init();
  return app;
} has no method 'createServer'
    at Object.<anonymous> (/root/0x10code/app.js:19:19)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

I'm running on Ubuntu 11.04 Natty. Any help is appreciated, thanks! I'm just testing some performance optimisations.

**Comment by mappum** [comment]
Looks like you didn't install express. Do `npm install express`.

**Comment by wub** [comment]
Yeah, had tried that, tried it globally, as well. Still no luck. Anywhere else I should check?

**Comment by mappum** [comment]
I'm not sure, it usually succeeds right away. Are you using an old version of node? You may want to update.

**Comment by wub** [comment]
Running v0.6.15, I'll recompile and see if there's any notifications.

As a side note, I'm hosting your CSS and JS on the Rackspace CDN, so if you want to link to those and take some load off the server/bandwidth, just link to these:

`http://c329741.r41.cf1.rackcdn.com/library.css`
`http://c329741.r41.cf1.rackcdn.com/library.js`

Doesn't cost me much, so feel free to let me know if there's anything else you want hosted ;)

**Comment by mappum** [comment]
Holy shit, thanks. This isn't some sort of scam where you insert your own scripts into the code, is it? >:/

Oh well, I'm linking it anyway.

**Comment by wub** [comment]
No sir, if you want, I can make you a sub-account/give you access? As I've not been able to test the code, it may not work - a private testing instance may be a good idea, haha.

That's why I've been trying to get this one working!

What are the specs on your current 0x10co.de VPS, if you don't mind?

**Comment by mappum** [comment]
I just got a free VPS from some other guy (that I haven't moved to yet), which is 2g ram and 6x2.4ghz CPU.

**Comment by wub** [comment]
Ok cool, I think I saw that on Twitter.

I'll let you know if my manual compilations are a success!

I have some 2GB Quad  Xeon 3.4GHz ones if you need 'em for anything, I'm certainly not using them at the moment.

**Comment by mappum** [comment]
How can you afford this if you only do open source stuff (if you don't mind me asking?

**Comment by wub** [comment]
I've a full time job for a development/marketing government contractor here in New Zealand, I'm currently running with very little expenses, and I want to see deserving projects get pushed as far as they can!

**Comment by mappum** [comment]
Good Guy Jarrod.

**Comment by wub** [comment]
If you want access to the CDN, so you can be sure I'm not hax0ring, let me know (jarrod.mosen@me.com). Also, perhaps this could be a good starting style (throw it over Bootstrap) for the site? http://bootswatch.com/cyborg/ Seems to fit with the 0x10c theme.

**Comment by Twisol** [comment]
I'll throw in a +1 for that awesome theme.

**Comment by jazzychad** [comment]
Nice, that's the theme (cyborg) I'm using for dcpubin.com
