### ISSUE TITLE
403 retrieving dcpu16.js from github

### ISSUE THREAD

**Issue by keyz182** [mappum/0x10code#2]
In Chrome on Windows 7 (64bit) loading the page with the Chrome inspector open shows that https://raw.github.com/mappum/DCPU-16/master/dcpu16.js is throwing a 403. 

Possibly github blocking so many requests to a raw file from an external site (I don't know their policy on this)?

**Comment by mappum** [comment]
Yeah, that wasn't my best idea. I didn't realize I was going to get 10 requests per second.

**Comment by keyz182** [comment]
Heh, yup, you got Notch'd. Hosting on the same server as you Minecraft server?

**Comment by mappum** [comment]
I started hosting this myself. Sorry, Github.
