### ISSUE TITLE
Loading 0xe010 into character displays nothing

### ISSUE THREAD

**Issue by nluqo** [mappum/0x10code#22]
No idea what's going on here. I'm simply trying to set a font word. It fails when setting to 0xe010. If I set it with a literal value, it works. If I change 0xe010 to anything else, it works.

http://0x10co.de/5j03d

**Comment by darkhog** [comment]
Simple newbie mistake - wrong instruction order. All program data (strings, fonts, level layouts, etc.) should be AFTER actual code (unless you need to change them in runtime). This works: http://0x10co.de/l0rn2

**Comment by nluqo** [comment]
Derp. Of course. PC starts at 0.
