### ISSUE TITLE
Extreme browser lag HWI

### ISSUE THREAD

**Issue by tjohnman** [mappum/0x10code#40]
Whenever I call HWI repeatedly (in a loop), no matter to which virtual device, the browser window starts lagging to the point of being unusable.

Happens on Chrome, Firefox and Safari in Mac OS X 10.6.8. Also on Windows 7 64bit.

dEgle95 provided an example program:
http://0x10co.de/ymlgk

**Comment by mappum** [comment]
This was fixed with commit 73c813e.
