### ISSUE TITLE
Create readme with instructions on how to host own server.

### ISSUE THREAD

**Issue by TyOverby** [mappum/0x10code#5]
Especially with the server being pounded due to Notch's tweet, it has become clear that private servers are going to be useful.

Obviously this is a node.js server, but with the javascript files named program.js or javascript.js, I honestly don't know where to start.

**Comment by mappum** [comment]
The server isn't getting much traffic now, but if you still want to, you need to make a copy of the example conf (`config_example.js`) and name it `config.js`, install mongodb, then just run `node app.js`. The server will be running on port 80.

**Comment by wub** [comment]
I'd be happy to bulletproof you against any other surges; shameless plug:  http://en.gs/

I can hook you up to Akamai and get it running a bit leaner, too, if you'd like! Just say the word and I'll fork it and do it.
