### ISSUE TITLE
Doesn't detect all hardware devices.

### ISSUE THREAD

**Issue by ghost** [mappum/0x10code#61]
If one has a loop like:

``` dasm
HWN Z

:hw
  HWQ Z
  SUB Z, 1
  SET PC, hw
```

Not all the hardware devices will be detected by `HWQ`. For the first iteration in the loop, none of the registers that `HWQ` sets will actually be set. And only on the second and subsequent iterations will these registers be set.

**Comment by mappum** [comment]
The device indexes range from 0 to HWN-1, so this is a bug with your code. Just do `SUB Z, 1` before the `HWQ` rather than after.
.
