### ISSUE TITLE
[label + 1] doesn't work

### ISSUE THREAD

**Issue by hfxdesign** [mappum/0x10code#67]
When using a label for memory location and setting the offest to + 1 like so:

SET [LABEL + 0x1], 0xFFAA

I get this: "Assembler error: Invalid offset pointer, must have 1 literal/subroutine and 1 register"

However, if I use ADD instead of +, it works just fine.

**Comment by cassiebeckley** [comment]
First, by "subroutine" the error message means "label".

Labels are actually replaced with literals by the parser. So, `[LABEL + 0x1]` is basically just saying `[0x2 + 0x1]` (if `LABEL` is `0x2`.)

The [spec](http://dcpu.com/dcpu-16/) only deals with offset pointers with 1 register and 1 literal. Your example provides 2 literals.
