### ISSUE TITLE
console output not working after save

### ISSUE THREAD

**Issue by jazzychad** [mappum/0x10code#7]
Console output works fine in edit mode, but after saving, sometimes nothing will be output to the console (maybe b/c of breaking only after a few thousand cycles?).

examples:
http://0x10co.de/83379 - same as http://dcpubin.com/puTIqosed
http://0x10co.de/vtas - same as http://dcpubin.com/ee2kkbeuJ

**Comment by mappum** [comment]
That's just because the display spec was changed, and now the default color is black on black. Read more about it [here](http://0x10co.de/io).

**Comment by jazzychad** [comment]
Ah, I see. Fair enough. Seems like a high barrier for getting basic console output, since each character will need some extra bits to see. This makes doing a basic strcpy from a DAT string much more complicated. Maybe white on black would be a saner default if all the color bits are 0. Dunno, it's up to you of course. Keep up the good work.

**Comment by mappum** [comment]
all you will have to do is BOR the character value with 0xf000 to make it white on black.

**Comment by jazzychad** [comment]
ok, cool. wrote a demo program based on notch's example: http://0x10co.de/syjl7

on the first run, it prints strangely (some characters are not printed correctly). but if i open the debug dropdown and hit run again, it works fine. same behavior in chrome and safari.

**Comment by mappum** [comment]
I am migrating to a new character drawing system, so this (hopefully) won't be a problem.
