### ISSUE TITLE
Aaaand it's down

### ISSUE THREAD

**Issue by onbjerg** [mappum/0x10code#78]

**Comment by mappum** [comment]
Yep, and it's been down for a few years. Considering that Notch is no longer working on 0x10c, it doesn't seem worth it to keep the site up anymore. But since it's open source, you can feel free to host your own :smile:

**Comment by onbjerg** [comment]
Then at least release the domain as well 💃

**Comment by Zardoz89** [comment]
Techcompilant it's following the path of 0x10c, even Noth give some support.

**Comment by paultech** [comment]
Is the database available? We'd be happy to host it on our infrastructure 
(techcompliant)

**Comment by onbjerg** [comment]
@Zardoz89 Totally unrelated to this issue that is well over 3 months old.
